# Generated by Django 2.2.8 on 2020-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200719_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirts'), ('SW', 'Sportswear'), ('OW', 'Outerwear')], max_length=2),
        ),
    ]
