# Generated by Django 2.2.8 on 2020-07-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200719_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ST', 'Starters'), ('MD', 'Main dishes'), ('DS', 'Desserts'), ('DR', 'Drinks')], max_length=2),
        ),
    ]
