# Generated by Django 2.2.8 on 2020-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgsrc',
            field=models.TextField(default='www.google.come'),
            preserve_default=False,
        ),
    ]
