# Generated by Django 2.2.8 on 2020-07-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='imgsrc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
