# Generated by Django 2.2.8 on 2020-08-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_item_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('P', 'Popular'), ('D', 'Discount')], max_length=1, null=True),
        ),
    ]
