# Generated by Django 2.2.8 on 2020-08-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200801_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ST', 'Starters'), ('MD', 'Main dishes'), ('DS', 'Desserts'), ('DR', 'Drinks')], max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('V', 'Vegan'), ('GF', 'Gluten-free'), ('MS', 'Michelin-starred')], max_length=5, null=True),
        ),
    ]
