# Generated by Django 2.2.8 on 2020-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200801_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main dishes', 'Main dishes'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Gluten Free', 'Gluten-free'), ('Michelin Starred', 'Michelin-starred')], max_length=30, null=True),
        ),
    ]
